### ISSUE TITLE
Pipeline processes the middle square inside of a frame

### ISSUE THREAD

**Issue by farbodf** [farbodf/closing-credits-recognizer#1]
At the moment all frames are cut in way so that the middle square is extracted out of the frame like the following picture:

![IMG_0131](https://user-images.githubusercontent.com/5970533/58819298-ee22f800-85fd-11e9-89bd-914c09c64dfd.jpg)

This is problematic in cases where the credits are not shown in the middle of the frame. For example:

![IMG_0132](https://user-images.githubusercontent.com/5970533/58819358-098e0300-85fe-11e9-94b2-ec27d3bfcdfe.jpg)

A change should be made so that these cases are handled properly.

**Comment by parallel-places** [comment]
Fixed!
